#!/usr/bin/env python3
"""Regenerate every physician-derived surface from data/physicians.json.

Usage:  python3 scripts/update-physicians.py

The JSON file is the single source of truth for the roster and its
display order. This script rewrites:

  1. index.html            — team grid, "N Expert Physicians" stat,
                             Physician schema graph
  2. doctors/index.html    — team cards, ItemList schema
  3. every *.html           — the tp-docrow physician link row

Individual profile pages (doctors/<slug>/index.html) are authored by
hand and are NOT touched; adding a doctor here still requires creating
their profile page and a sitemap entry.
"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = json.loads((ROOT / "data/physicians.json").read_text())["physicians"]
N = len(DOCS)

def swap(text, start, end, replacement, label):
    pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    out, n = pat.subn(start + "\n" + replacement + "\n" + end, text)
    if n != 1:
        sys.exit(f"ERROR: marker {label!r} matched {n} times")
    return out

# ---------------------------------------------------------------- index.html
idx = (ROOT / "index.html").read_text()

delays = ["", " d1", " d2"]
cards = []
for i, d in enumerate(DOCS):
    cards.append(f"""      <div class="reveal{delays[i % 3]}">
        <div class="team-portrait"><div class="ph"><span class="ph-mono" aria-hidden="true">C</span><div class="ph-name">{d['name']}</div></div></div>
        <p class="team-role">{d['role']}</p>
        <h3 class="team-name">{d['name']}</h3>
        <p class="team-cert">{d['cert']}</p>
        <p class="team-bio">{d['bio']}</p>
        <a class="team-prof-link" href="doctors/{d['slug']}/">View profile →</a>
      </div>""")
grid = '    <div class="team-grid">\n' + "\n".join(cards) + "\n    </div>"
idx = swap(idx, "<!-- physicians:grid:start (generated by scripts/update-physicians.py) -->",
           "<!-- physicians:grid:end -->", grid, "grid")

graph = json.dumps({
    "@context": "https://schema.org",
    "@graph": [
        {"@type": "Physician",
         "@id": f"https://canvas-medical.com/#dr-{d['slug']}",
         "name": d["name"],
         "medicalSpecialty": d["specialty"],
         "url": f"https://canvas-medical.com/doctors/{d['slug']}/",
         "worksFor": {"@id": "https://canvas-medical.com/#clinic"}}
        for d in DOCS
    ]}, ensure_ascii=False, indent=2)
idx = swap(idx, "<!-- physicians:graph:start -->", "<!-- physicians:graph:end -->",
           f'<script type="application/ld+json">\n{graph}\n</script>', "graph")

idx, n = re.subn(
    r'<div class="stat"><div class="stat-n">\d+</div><div class="stat-l">Expert Physicians</div></div>',
    f'<div class="stat"><div class="stat-n">{N}</div><div class="stat-l">Expert Physicians</div></div>',
    idx)
if n != 1:
    sys.exit(f"ERROR: physician stat matched {n} times")

form_opts = "\n".join(f"              <option>{d['short']}</option>" for d in DOCS)
idx = swap(idx, "<!-- physicians:form:start -->", "<!-- physicians:form:end -->",
           form_opts, "form")
(ROOT / "index.html").write_text(idx)
print(f"index.html: grid ({N} cards), schema graph, stat = {N}, form options = {N}")

# ---------------------------------------------------------- doctors/index.html
hub = (ROOT / "doctors/index.html").read_text()
hubcards = "\n".join(
    f'        <a class="tp-card" href="{d["slug"]}/">\n'
    f'          <h3>{d["name"]}</h3>\n'
    f'          <p>{d["hub_desc"]}</p>\n'
    f'        </a>' for d in DOCS)
hub = swap(hub, "<!-- physicians:hubcards:start -->", "<!-- physicians:hubcards:end -->",
           hubcards, "hubcards")

itemlist = json.dumps({
    "@context": "https://schema.org", "@type": "ItemList",
    "name": "CANVAS Medical Clinic Physicians",
    "itemListElement": [
        {"@type": "ListItem", "position": i + 1,
         "url": f"https://canvas-medical.com/doctors/{d['slug']}/", "name": d["name"]}
        for i, d in enumerate(DOCS)
    ]}, ensure_ascii=False, indent=2)
hub = swap(hub, "<!-- physicians:itemlist:start -->", "<!-- physicians:itemlist:end -->",
           f'<script type="application/ld+json">\n{itemlist}\n</script>', "itemlist")
(ROOT / "doctors/index.html").write_text(hub)
print(f"doctors/index.html: {N} cards, ItemList")

# --------------------------------------------------------------- tp-docrow
docrow_re = re.compile(
    r'(<nav class="tp-docrow" aria-label="Our physicians">\n)(.*?)(\s*<a href="([^"]*?)doctors/" class="all">)',
    re.S)
count = 0
for f in ROOT.rglob("*.html"):
    s = f.read_text()
    if "tp-docrow" not in s:
        continue
    def repl(m):
        prefix = m.group(4)
        links = "".join(f'        <a href="{prefix}doctors/{d["slug"]}/">{d["short"]}</a>\n' for d in DOCS)
        return m.group(1) + links + m.group(3).lstrip("\n")
    s2, n = docrow_re.subn(repl, s)
    if n and s2 != s:
        f.write_text(s2)
        count += 1
print(f"tp-docrow: rewritten in {count} pages")

# --------------------------------------------------------------- sanity
missing = [d["slug"] for d in DOCS if not (ROOT / "doctors" / d["slug"] / "index.html").exists()]
if missing:
    print(f"WARNING: no profile page for: {missing} — create doctors/<slug>/index.html and add to sitemap.xml")
print("done")
